package vista;

import persistencia.PeliculaData;
import modelo.Pelicula;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * @author Juan Manuel, Nerina, Nahuel, Alaina, Juan Ignacio, Tiziana
 */
public class Cartelera extends javax.swing.JInternalFrame {

    private PeliculaData peliculaData;
    private DefaultTableModel modeloTablaCartelera;
    private DefaultTableModel modeloTablaEstrenos;

    public Cartelera() {
        initComponents();
        peliculaData = new PeliculaData();
        configurarTablas();
        cargarDatos();
    }

    private void configurarTablas() {
        String[] columnas = {"Título", "Director", "Actores", "Género", "Origen", "Estreno"};

        // Configurar tabla de cartelera
        modeloTablaCartelera = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaCartelera.setModel(modeloTablaCartelera);

        // Configurar tabla de próximos estrenos
        modeloTablaEstrenos = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaEstrenos.setModel(modeloTablaEstrenos);
    }

    private void cargarDatos() {
        cargarCartelera();
        cargarProximosEstrenos();
    }

    private void cargarCartelera() {
        modeloTablaCartelera.setRowCount(0);
        List<Pelicula> peliculas = peliculaData.listarPeliculasEnCartelera();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        for (Pelicula pelicula : peliculas) {
            Object[] fila = {
                pelicula.getTitulo(),
                pelicula.getDirector(),
                pelicula.getActores(),
                pelicula.getGenero(),
                pelicula.getOrigen(),
                pelicula.getEstreno() != null ? pelicula.getEstreno().format(formatter) : "N/A"
            };
            modeloTablaCartelera.addRow(fila);
        }
    }

    private void cargarProximosEstrenos() {
        modeloTablaEstrenos.setRowCount(0);
        List<Pelicula> peliculas = peliculaData.listarProximosEstrenos();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        for (Pelicula pelicula : peliculas) {
            Object[] fila = {
                pelicula.getTitulo(),
                pelicula.getDirector(),
                pelicula.getActores(),
                pelicula.getGenero(),
                pelicula.getOrigen(),
                pelicula.getEstreno() != null ? pelicula.getEstreno().format(formatter) : "N/A"
            };
            modeloTablaEstrenos.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        titleCartelera = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        tabEnCartelera = new javax.swing.JPanel();
        scrollCartelera = new javax.swing.JScrollPane();
        tablaCartelera = new javax.swing.JTable();
        tabProximosEstrenos = new javax.swing.JPanel();
        scrollEstrenos = new javax.swing.JScrollPane();
        tablaEstrenos = new javax.swing.JTable();

        panelTitulo.setBackground(new java.awt.Color(51, 90, 144));
        panelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleCartelera.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleCartelera.setForeground(new java.awt.Color(255, 255, 255));
        titleCartelera.setText("Cartelera");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCartelera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCartelera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tablaCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Director", "Actores", "Género", "Origen", "Estreno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollCartelera.setViewportView(tablaCartelera);

        javax.swing.GroupLayout tabEnCarteleraLayout = new javax.swing.GroupLayout(tabEnCartelera);
        tabEnCartelera.setLayout(tabEnCarteleraLayout);
        tabEnCarteleraLayout.setHorizontalGroup(
            tabEnCarteleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnCarteleraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCartelera, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabEnCarteleraLayout.setVerticalGroup(
            tabEnCarteleraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEnCarteleraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCartelera, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("En Cartelera", tabEnCartelera);

        tablaEstrenos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Director", "Actores", "Género", "Origen", "Estreno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollEstrenos.setViewportView(tablaEstrenos);

        javax.swing.GroupLayout tabProximosEstrenosLayout = new javax.swing.GroupLayout(tabProximosEstrenos);
        tabProximosEstrenos.setLayout(tabProximosEstrenosLayout);
        tabProximosEstrenosLayout.setHorizontalGroup(
            tabProximosEstrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProximosEstrenosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollEstrenos, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabProximosEstrenosLayout.setVerticalGroup(
            tabProximosEstrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProximosEstrenosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollEstrenos, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Próximos Estrenos", tabProximosEstrenos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollCartelera;
    private javax.swing.JScrollPane scrollEstrenos;
    private javax.swing.JPanel tabEnCartelera;
    private javax.swing.JPanel tabProximosEstrenos;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tablaCartelera;
    private javax.swing.JTable tablaEstrenos;
    private javax.swing.JLabel titleCartelera;
    // End of variables declaration//GEN-END:variables
}
