/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Neri
 */
public class Principal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pelicula
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneltitulo = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        fondocentral = new javax.swing.JDesktopPane();
        panelfinal = new javax.swing.JPanel();
        labelfechahora = new javax.swing.JLabel();
        labelestado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mGestion = new javax.swing.JMenu();
        mPeliculas = new javax.swing.JMenuItem();
        mSalas = new javax.swing.JMenuItem();
        mFunciones = new javax.swing.JMenuItem();
        mTickets = new javax.swing.JMenuItem();
        mHelp = new javax.swing.JMenu();
        mAcerca = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 51, 255));

        paneltitulo.setBackground(new java.awt.Color(51, 90, 144));

        title.setBackground(#263238);
        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Gestor de Cine");

        javax.swing.GroupLayout paneltituloLayout = new javax.swing.GroupLayout(paneltitulo);
        paneltitulo.setLayout(paneltituloLayout);
        paneltituloLayout.setHorizontalGroup(
            paneltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltituloLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(213, 213, 213))
        );
        paneltituloLayout.setVerticalGroup(
            paneltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltituloLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(title)
                .addContainerGap())
        );

        fondocentral.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout fondocentralLayout = new javax.swing.GroupLayout(fondocentral);
        fondocentral.setLayout(fondocentralLayout);
        fondocentralLayout.setHorizontalGroup(
            fondocentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fondocentralLayout.setVerticalGroup(
            fondocentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        panelfinal.setBackground(new java.awt.Color(51, 90, 144));
        panelfinal.setForeground([51,90,144]);

        labelfechahora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelfechahora.setForeground(new java.awt.Color(255, 255, 255));
        labelfechahora.setText("Fecha y hora:");

        labelestado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelestado.setForeground(new java.awt.Color(255, 255, 255));
        labelestado.setText("Estado:");

        javax.swing.GroupLayout panelfinalLayout = new javax.swing.GroupLayout(panelfinal);
        panelfinal.setLayout(panelfinalLayout);
        panelfinalLayout.setHorizontalGroup(
            panelfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfinalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelestado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelfechahora)
                .addGap(102, 102, 102))
        );
        panelfinalLayout.setVerticalGroup(
            panelfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfinalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelestado)
                    .addComponent(labelfechahora))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mArchivo.setText("Archivo");

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mSalir);

        jMenuBar1.add(mArchivo);

        mGestion.setText("Gestion");

        mPeliculas.setText("Peliculas");
        mPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPeliculasActionPerformed(evt);
            }
        });
        mGestion.add(mPeliculas);

        mSalas.setText("Salas");
        mGestion.add(mSalas);

        mFunciones.setText("Funciones");
        mFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFuncionesActionPerformed(evt);
            }
        });
        mGestion.add(mFunciones);

        mTickets.setText("Tickets");
        mTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTicketsActionPerformed(evt);
            }
        });
        mGestion.add(mTickets);

        jMenuBar1.add(mGestion);

        mHelp.setText("Ayuda");

        mAcerca.setText("Acerca de...");
        mHelp.add(mAcerca);

        jMenuBar1.add(mHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondocentral, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelfinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondocentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSalirActionPerformed

    private void mPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mPeliculasActionPerformed

    private void mFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFuncionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mFuncionesActionPerformed

    private void mTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTicketsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane fondocentral;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelestado;
    private javax.swing.JLabel labelfechahora;
    private javax.swing.JMenuItem mAcerca;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenuItem mFunciones;
    private javax.swing.JMenu mGestion;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenuItem mPeliculas;
    private javax.swing.JMenuItem mSalas;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mTickets;
    private javax.swing.JPanel panelfinal;
    private javax.swing.JPanel paneltitulo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
