/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JInternalFrame;

/**
 *
 * @author Neri
 */
public class Principal extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pelicula
     */
    
    public Principal() {
        initComponents();
        configurarVentana();
        inicializarBarraEstado();
    }
    
    private void configurarVentana() {
        this.setTitle("Cinema Centro");
        this.setClosable(false);
        this.setMaximizable(true);
        this.setResizable(true);
    }
    
    private void inicializarBarraEstado() {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        String fechaHora = LocalDateTime.now().format(formato);
        labelfechahora.setText("Sesión iniciada: " + fechaHora);
        labelestado.setText("Estado: Sistema listo");
    }
    
    private void actualizarEstado(String estado) {
        labelestado.setText("Estado: " + estado);
    }
    
    private void abrirVentanaInterna(JInternalFrame ventana) {
        JInternalFrame[] ventanas = fondocentral.getAllFrames();
        for (JInternalFrame v : ventanas) {
            v.dispose();
        }

        fondocentral.add(ventana);
        ventana.setVisible(true);

        int x = (fondocentral.getWidth() - ventana.getWidth()) / 2;
        int y = (fondocentral.getHeight() - ventana.getHeight()) / 2;
        ventana.setLocation(x, y);

        actualizarEstado("Ventana activa: " + ventana.getTitle());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneltitulo = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        fondocentral = new javax.swing.JDesktopPane();
        panelfinal = new javax.swing.JPanel();
        labelfechahora = new javax.swing.JLabel();
        labelestado = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mGestion = new javax.swing.JMenu();
        mPeliculas = new javax.swing.JMenuItem();
        mSalas = new javax.swing.JMenuItem();
        mFunciones = new javax.swing.JMenuItem();
        mAsientos = new javax.swing.JMenuItem();
        mTickets = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        mAcerca = new javax.swing.JMenuItem();
        mReportes = new javax.swing.JMenu();
        mVentas = new javax.swing.JMenuItem();
        mPelismas = new javax.swing.JMenuItem();
        mCompradores = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();
        mitenShortcut = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(51, 51, 255));

        paneltitulo.setBackground(new java.awt.Color(51, 90, 144));
        paneltitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Gestor de Cine");

        javax.swing.GroupLayout paneltituloLayout = new javax.swing.GroupLayout(paneltitulo);
        paneltitulo.setLayout(paneltituloLayout);
        paneltituloLayout.setHorizontalGroup(
            paneltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(213, 213, 213))
        );
        paneltituloLayout.setVerticalGroup(
            paneltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltituloLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(title)
                .addContainerGap())
        );

        fondocentral.setBackground(java.awt.SystemColor.controlHighlight);
        fondocentral.setPreferredSize(new java.awt.Dimension(0, 650));

        javax.swing.GroupLayout fondocentralLayout = new javax.swing.GroupLayout(fondocentral);
        fondocentral.setLayout(fondocentralLayout);
        fondocentralLayout.setHorizontalGroup(
            fondocentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        fondocentralLayout.setVerticalGroup(
            fondocentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelfinal.setBackground(new java.awt.Color(51, 90, 144));

        labelfechahora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelfechahora.setForeground(new java.awt.Color(255, 255, 255));
        labelfechahora.setText("Fecha y hora:");

        labelestado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelestado.setForeground(new java.awt.Color(255, 255, 255));
        labelestado.setText("Estado:");

        javax.swing.GroupLayout panelfinalLayout = new javax.swing.GroupLayout(panelfinal);
        panelfinal.setLayout(panelfinalLayout);
        panelfinalLayout.setHorizontalGroup(
            panelfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfinalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelestado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelfechahora)
                .addGap(102, 102, 102))
        );
        panelfinalLayout.setVerticalGroup(
            panelfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfinalLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelfinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelestado)
                    .addComponent(labelfechahora))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mGestion.setBackground(java.awt.SystemColor.controlHighlight);
        mGestion.setText("Gestion");

        mPeliculas.setText("Peliculas");
        mPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPeliculasActionPerformed(evt);
            }
        });
        mGestion.add(mPeliculas);

        mSalas.setText("Salas");
        mSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalasActionPerformed(evt);
            }
        });
        mGestion.add(mSalas);

        mFunciones.setText("Funciones");
        mFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFuncionesActionPerformed(evt);
            }
        });
        mGestion.add(mFunciones);

        mAsientos.setText("Asientos");
        mAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAsientosActionPerformed(evt);
            }
        });
        mGestion.add(mAsientos);

        mTickets.setText("Tickets");
        mTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTicketsActionPerformed(evt);
            }
        });
        mGestion.add(mTickets);

        menuBar.add(mGestion);

        mClientes.setText("Usuarios");

        mAcerca.setText("Clientes");
        mAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAcercaActionPerformed(evt);
            }
        });
        mClientes.add(mAcerca);

        menuBar.add(mClientes);

        mReportes.setText("Reportes");

        mVentas.setText("Ventas");
        mVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVentasActionPerformed(evt);
            }
        });
        mReportes.add(mVentas);

        mPelismas.setText("Peliculas mas vistas");
        mPelismas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPelismasActionPerformed(evt);
            }
        });
        mReportes.add(mPelismas);

        mCompradores.setText("Compradores");
        mCompradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCompradoresActionPerformed(evt);
            }
        });
        mReportes.add(mCompradores);

        menuBar.add(mReportes);

        mSalir.setText("Salir");

        mitenShortcut.setText("Salir");
        mitenShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitenShortcutActionPerformed(evt);
            }
        });
        mSalir.add(mitenShortcut);

        menuBar.add(mSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fondocentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
            .addComponent(panelfinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fondocentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVentasActionPerformed
        actualizarEstado("Reporte de ventas - En desarrollo");
        javax.swing.JOptionPane.showMessageDialog(this, "Reporte de ventas en desarrollo", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mVentasActionPerformed

    private void mPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPeliculasActionPerformed
        Pelicula ventanaPeliculas = new Pelicula();
        abrirVentanaInterna(ventanaPeliculas);
    }//GEN-LAST:event_mPeliculasActionPerformed

    private void mFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFuncionesActionPerformed
        Funcion ventanaFunciones = new Funcion();
        abrirVentanaInterna(ventanaFunciones);
    }//GEN-LAST:event_mFuncionesActionPerformed

    private void mTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTicketsActionPerformed
        Tickets ventanaTickets = new Tickets();
        abrirVentanaInterna(ventanaTickets);
    }//GEN-LAST:event_mTicketsActionPerformed

    private void mPelismasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPelismasActionPerformed
        actualizarEstado("Reporte de películas más vistas - En desarrollo");
        javax.swing.JOptionPane.showMessageDialog(this, "Reporte de películas más vistas en desarrollo",  "Información",  javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mPelismasActionPerformed

    private void mCompradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCompradoresActionPerformed
        Compradores ventanaCompradores = new Compradores();
        abrirVentanaInterna(ventanaCompradores);
    }//GEN-LAST:event_mCompradoresActionPerformed

    private void mitenShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitenShortcutActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(this,"¿Está seguro que desea salir del sistema?","Confirmar salida", 
                        javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE );
        
        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mitenShortcutActionPerformed

    private void mSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalasActionPerformed
        Salas ventanaSalas = new Salas();
        abrirVentanaInterna(ventanaSalas);
    }//GEN-LAST:event_mSalasActionPerformed

    private void mAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAcercaActionPerformed
        Usuario ventanUsuario = new Usuario();
        abrirVentanaInterna(ventanUsuario);
    }//GEN-LAST:event_mAcercaActionPerformed

    private void mAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAsientosActionPerformed
        Asientos ventanaAsientos = new Asientos();
        abrirVentanaInterna(ventanaAsientos);
        try {
            ventanaAsientos.setMaximum(true);
        } catch (java.beans.PropertyVetoException e) {
            System.out.println("No se pudo maximizar la ventana: " + e.getMessage());
        }
    }//GEN-LAST:event_mAsientosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane fondocentral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelestado;
    private javax.swing.JLabel labelfechahora;
    private javax.swing.JMenuItem mAcerca;
    private javax.swing.JMenuItem mAsientos;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem mCompradores;
    private javax.swing.JMenuItem mFunciones;
    private javax.swing.JMenu mGestion;
    private javax.swing.JMenuItem mPeliculas;
    private javax.swing.JMenuItem mPelismas;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenuItem mSalas;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem mTickets;
    private javax.swing.JMenuItem mVentas;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mitenShortcut;
    private javax.swing.JPanel panelfinal;
    private javax.swing.JPanel paneltitulo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
