/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import persistencia.SalaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Neri
 */
public class Sala extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sala
     */
    private SalaData salaData;
    private DefaultTableModel modeloTabla;
    private modelo.Sala salaSeleccionada;
    
    public Sala() {
        initComponents();
        salaData = new SalaData();
        modeloTabla = (DefaultTableModel) ID.getModel();
        salaSeleccionada = null;
        configurarTabla();
        cargarTabla();
        configurarEventos();
    }
    
    private void configurarTabla() {
        modeloTabla.setRowCount(0);
        modeloTabla.setColumnCount(0);
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Apta 3D");
        modeloTabla.addColumn("Capacidad");
        modeloTabla.addColumn("Estado");
        modeloTabla.addColumn("Activo");
    }

    private void cargarTabla() {
        modeloTabla.setRowCount(0);
        for (modelo.Sala sala : salaData.listarSalas()) {
            Object[] fila = {
                sala.getNroSala(),
                sala.isApta3D() ? "Sí" : "No",
                sala.getCapacidad(),
                sala.getEstado(),
                sala.isActivo() ? "Activo" : "Inactivo"
            };
            modeloTabla.addRow(fila);
        }
    }
    
    private void configurarEventos() {
        ID.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && ID.getSelectedRow() != -1) {
                cargarDatosSala();
            }
        });
    }
    
    private void cargarDatosSala() {
        int filaSeleccionada = ID.getSelectedRow();
        if (filaSeleccionada != -1) {
            int nroSala = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
            salaSeleccionada = salaData.buscarSala(nroSala);

            if (salaSeleccionada != null) {
                campo1.setText(String.valueOf(salaSeleccionada.getNroSala()));
                campo2.setText(String.valueOf(salaSeleccionada.getCapacidad()));
                campo3.setText(salaSeleccionada.isApta3D() ? "Sí" : "No");
                campo4.setText(salaSeleccionada.getEstado());
                campo5.setText("N/A"); // Función asignada (pendiente de implementar)
            }
        }
    }
    
    private void limpiarCampos() {
        campo1.setText("");
        campo2.setText("");
        campo3.setText("");
        campo4.setText("");
        campo5.setText("");
        salaSeleccionada = null;
        ID.clearSelection();
    }
    
    private boolean validarCampos() {
        if (campo2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La capacidad es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            int capacidad = Integer.parseInt(campo2.getText().trim());
            if (capacidad <= 0) {
                JOptionPane.showMessageDialog(this, "La capacidad debe ser mayor a 0","Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un número válido","Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (campo3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El tipo de proyección es obligatorio (Sí/No)", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (campo4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,"El estado es obligatorio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltitulo = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        tablebutton = new javax.swing.JPanel();
        buttonEdit = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonAgg = new javax.swing.JButton();
        buttonVer = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        ID = new javax.swing.JTable();
        panelbutton = new javax.swing.JPanel();
        buttonActualizar = new javax.swing.JButton();
        buttonGuardar = new javax.swing.JButton();
        buttonlimpiar = new javax.swing.JButton();
        panelInfo = new javax.swing.JPanel();
        titleDetalles = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelCapacidad = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        labelFuncionAg = new javax.swing.JLabel();
        campo1 = new javax.swing.JTextField();
        campo2 = new javax.swing.JTextField();
        campo3 = new javax.swing.JTextField();
        campo4 = new javax.swing.JTextField();
        campo5 = new javax.swing.JTextField();

        paneltitulo.setBackground(new java.awt.Color(51, 90, 144));
        paneltitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Gestion de Salas");

        javax.swing.GroupLayout paneltituloLayout = new javax.swing.GroupLayout(paneltitulo);
        paneltitulo.setLayout(paneltituloLayout);
        paneltituloLayout.setHorizontalGroup(
            paneltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltituloLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltituloLayout.setVerticalGroup(
            paneltituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltituloLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(title)
                .addContainerGap())
        );

        tablebutton.setBackground(java.awt.SystemColor.controlHighlight);

        buttonEdit.setText("Editar");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonAgg.setText("Agregar Sala");
        buttonAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAggActionPerformed(evt);
            }
        });

        buttonVer.setText("Buscar");
        buttonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablebuttonLayout = new javax.swing.GroupLayout(tablebutton);
        tablebutton.setLayout(tablebuttonLayout);
        tablebuttonLayout.setHorizontalGroup(
            tablebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablebuttonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonAgg)
                .addGap(18, 18, 18)
                .addComponent(buttonEdit)
                .addGap(18, 18, 18)
                .addComponent(buttonEliminar)
                .addGap(18, 18, 18)
                .addComponent(buttonVer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablebuttonLayout.setVerticalGroup(
            tablebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablebuttonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(tablebuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonEliminar)
                    .addComponent(buttonAgg)
                    .addComponent(buttonVer))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        ID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Capacidad", "Tipo de sala", "Estado"
            }
        ));
        scroll.setViewportView(ID);

        buttonActualizar.setText("Actualizar");
        buttonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActualizarActionPerformed(evt);
            }
        });

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonlimpiar.setText("Limpiar");
        buttonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbuttonLayout = new javax.swing.GroupLayout(panelbutton);
        panelbutton.setLayout(panelbuttonLayout);
        panelbuttonLayout.setHorizontalGroup(
            panelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbuttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonActualizar)
                .addGap(42, 42, 42)
                .addComponent(buttonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(buttonlimpiar)
                .addGap(39, 39, 39))
        );
        panelbuttonLayout.setVerticalGroup(
            panelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbuttonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonActualizar)
                    .addComponent(buttonGuardar)
                    .addComponent(buttonlimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titleDetalles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleDetalles.setText("Detalles");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        labelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(102, 102, 102));
        labelNombre.setText("Nombre:");

        labelCapacidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCapacidad.setForeground(new java.awt.Color(102, 102, 102));
        labelCapacidad.setText("Capacidad:");

        labelTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTipo.setForeground(new java.awt.Color(102, 102, 102));
        labelTipo.setText("Tipo de proyeccion:");

        labelEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(102, 102, 102));
        labelEstado.setText("Estado:");

        labelFuncionAg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFuncionAg.setForeground(new java.awt.Color(102, 102, 102));
        labelFuncionAg.setText("Funcion asignada:");

        campo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleDetalles)
                    .addComponent(jLabel2)
                    .addGroup(panelInfoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(labelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo3))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                        .addComponent(labelCapacidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                        .addComponent(labelNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelInfoLayout.createSequentialGroup()
                                        .addComponent(labelEstado)
                                        .addGap(26, 26, 26)
                                        .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 64, Short.MAX_VALUE))
                            .addGroup(panelInfoLayout.createSequentialGroup()
                                .addComponent(labelFuncionAg)
                                .addGap(18, 18, 18)
                                .addComponent(campo5)))))
                .addContainerGap())
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleDetalles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCapacidad)
                    .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFuncionAg)
                    .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(panelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(panelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        if (salaSeleccionada == null) {
            JOptionPane.showMessageDialog(this,"Seleccione una sala de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        campo1.setEditable(false);
        JOptionPane.showMessageDialog(this, "Modifique los datos y presione Actualizar", "Editar Sala", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        if (salaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una sala de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro que desea eliminar la sala " + salaSeleccionada.getNroSala() + "?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            salaData.eliminarSala(salaSeleccionada.getNroSala());
            JOptionPane.showMessageDialog(this, "Sala eliminada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            cargarTabla();
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAggActionPerformed
        limpiarCampos();
        campo1.setEditable(false);
        JOptionPane.showMessageDialog(this, "Complete los datos y presione Guardar", "Agregar Sala", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonAggActionPerformed

    private void campo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo2ActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        if (!validarCampos()) {
            return;
        }

        modelo.Sala nuevaSala = new modelo.Sala();
        nuevaSala.setCapacidad(Integer.parseInt(campo2.getText().trim()));
        nuevaSala.setApta3D(campo3.getText().trim().equalsIgnoreCase("Sí") || campo3.getText().trim().equalsIgnoreCase("Si"));
        nuevaSala.setEstado(campo4.getText().trim());
        nuevaSala.setActivo(true);

        salaData.insertarSala(nuevaSala);
        JOptionPane.showMessageDialog(this, "Sala guardada correctamente con ID: " + nuevaSala.getNroSala(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
        cargarTabla();
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActualizarActionPerformed
        if (salaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una sala de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validarCampos()) {
            return;
        }

        salaSeleccionada.setCapacidad(Integer.parseInt(campo2.getText().trim()));
        salaSeleccionada.setApta3D(campo3.getText().trim().equalsIgnoreCase("Sí") || campo3.getText().trim().equalsIgnoreCase("Si"));
        salaSeleccionada.setEstado(campo4.getText().trim());

        salaData.actualizarSala(salaSeleccionada);
        JOptionPane.showMessageDialog(this, "Sala actualizada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
        cargarTabla();
    }//GEN-LAST:event_buttonActualizarActionPerformed

    private void buttonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonlimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_buttonlimpiarActionPerformed

    private void buttonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerActionPerformed
        String input = JOptionPane.showInputDialog(this, "Ingrese el número de sala a buscar:", "Buscar Sala", JOptionPane.QUESTION_MESSAGE);
        if (input != null && !input.trim().isEmpty()) {
            try {
                int nroSala = Integer.parseInt(input.trim());
                modelo.Sala sala = salaData.buscarSala(nroSala);

                if (sala != null) {
                    salaSeleccionada = sala;
                    campo1.setText(String.valueOf(sala.getNroSala()));
                    campo2.setText(String.valueOf(sala.getCapacidad()));
                    campo3.setText(sala.isApta3D() ? "Sí" : "No");
                    campo4.setText(sala.getEstado());
                    campo5.setText("N/A");

                    // Seleccionar en la tabla
                    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                        if ((int) modeloTabla.getValueAt(i, 0) == nroSala) {
                            ID.setRowSelectionInterval(i, i);
                            break;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró sala con ID: " + nroSala, "No encontrado", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingrese un número válido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ID;
    private javax.swing.JButton buttonActualizar;
    private javax.swing.JButton buttonAgg;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonVer;
    private javax.swing.JButton buttonlimpiar;
    private javax.swing.JTextField campo1;
    private javax.swing.JTextField campo2;
    private javax.swing.JTextField campo3;
    private javax.swing.JTextField campo4;
    private javax.swing.JTextField campo5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelCapacidad;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFuncionAg;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelbutton;
    private javax.swing.JPanel paneltitulo;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel tablebutton;
    private javax.swing.JLabel title;
    private javax.swing.JLabel titleDetalles;
    // End of variables declaration//GEN-END:variables
}
